### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by Rudloff** [troyengel/Preloader#1]
Hello,

It would be nice to have a composer.json file so the extension can be installed with [Composer](https://getcomposer.org/).

**Comment by troyengel** [comment]
Sure, why not! I don't use Composer at all (I run everything from git trees), so help figure out what needs to be done. I'm reading this:

* https://getcomposer.org/doc/02-libraries.md

I *think* this is what our composer.json would look like?

````
{
    "name": "mediawiki/Preloader",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/troyengel/Preloader"
        }
    ],
    "require": {
        "mediawiki/Preloader": "master"
    }
}
````

...but something doesn't seem right. Is there a good example for another Mediawiki plugin compser.json that we can use as a template that you know about? Do we submit it to Packagist like they recommend as well?

**Comment by Rudloff** [comment]
The _repositories_ and _require_ fields are not useful here, but some required fields are missing. I will provide a PR with a valid composer.json.

(Here is a good example: https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FLiquidThreads/master/composer.json)

Publishing to Packagist is not mandatory but it makes your extension appear in Composer search results, which is pretty useful.

**Comment by troyengel** [comment]
Submitted, want to see how it looks when you try and use it?

* https://packagist.org/packages/troyengel/preloader

**Comment by Rudloff** [comment]
It works perfectly, thanks!

**Comment by troyengel** [comment]
Awesome! There's a message I see at the top of packagist "This package is not auto-updated. Please set up the GitHub Service Hook for Packagist so that it gets updated whenever you push!" - let me see what needs to be done to fix.

**Comment by Rudloff** [comment]
I think you can add the hook here: https://github.com/troyengel/Preloader/settings/hooks
Click on Add service > Packagist. Then fill the form with your Packagist token (you can leave the other fields empty) and submit the form.

This will update the package on Packagist as soon as you push on Github (vs. once per day).

**Comment by troyengel** [comment]
Yup, all set - they have a nice easy to follow doc, took only seconds - it's integrated now, future pushes will now update over there. I could push a whole new tag but I don't think it's necessary without an actual code change to make this work -- do you see any need to tag a new git version right now?

**Comment by Rudloff** [comment]
Composer can't target tags that don't include a composer.json file but it can target branches. So a new tag could be useful but it is not strictly necessary.

**Comment by troyengel** [comment]
Done, why not. :) It's showing up with the new tag on Packagist v1.2.2, working like a charm - thanks for the new feature!
